### ISSUE TITLE
Local source might not work with knative-lambda-runtime

### ISSUE THREAD

**Issue by solsson** [triggermesh/tm#63]
I did only a very quick test, but I couldn't get local source with `-f ./my-handler` to produce a working runtime. Probably some mistake on my side, so if we have a positive example we can close this issue.

**Comment by tzununbekov** [comment]
@solsson I've updated readme with lambda runtime and local source example, please check it. Also added small fix for possible issue for local paths.

**Comment by solsson** [comment]
The go example works. I also think I found the issue from yesterday, which isn't fixed by 39d0e97: It works if I `tm deploy service go-lambda -f .` but not if I do `tm deploy service go-lambda -f ./lambda/` from a parent folder.

In the latter case the workspace contains a `.done` and a folder `lambda`. I suppose that a DIRECTORY arg would be a workaround, but it feels strange.

**Comment by tzununbekov** [comment]
weird, I just checked this case with different paths (`.`, `./lambda/`, `lambda`, etc.) and everything worked fine. @solsson are you sure that you tested latest CLI version from master?

**Comment by tzununbekov** [comment]
Tested again, looks ok. Closing due to inactivity
